### ISSUE TITLE
Document is unclear and example code is empty

### ISSUE THREAD

**Issue by dzpt** [grizzly/AppRating#12]
I pumped into this and have no idea how to use it.
From the doc:

> That's it to get started. Setting AppRating up with this line uses some sensible default criterion (detailed below) and will present a rating prompt whenever they are met.

Then where's the detail below? 

After config app id with `AppRating.appID("12345678")` in AppDelegate, do i have to manually call `AppRating.showRatingAlert()` or `AppRating.rate()` after write down logic code like this:
```
if AppRating.daysUntilPrompt() == 0 {
AppRating.showRatingAlert()
}
```

Or the package automatically determine to show it in the proper time?

**Comment by grizzly** [comment]
It will be shown after a while, depending on your settings. You should call userDidSignificantEvent whenever your user did something important. Only if users did some key features in the app over some times you can be pretty sure that they tend to love your app. Most of the people which do not like an app, uninstall that app within a very short periode of time.

**Comment by BCtopics** [comment]
I agree the "Docs" are lacking on the Repo itself. However, if you take a look through the code it's fairly simple and documented well. I'd try that out :).
