### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by furiosFast** [grizzly/AppRating#16]
hi,
Can you add the support for Swift Package Manager?

Thank

**Comment by grizzly** [comment]
Working on it...

**Comment by furiosFast** [comment]
something like this:
let package = Package(
    name: "AppRating",
    platforms: [
        .iOS(.v12), .macOS(.v10_5)
    ],
    products: [
        .library(name: "AppRating", targets: ["AppRating"]),
    ],
    targets: [
        .target(name: "AppRating", path: "AppRating"),
    ],
    swiftLanguageVersions: [.v4]
)

**Comment by grizzly** [comment]
I am working on it on the branch https://github.com/grizzly/AppRating/tree/feature/SwiftPackageManger .

**Comment by furiosFast** [comment]
it works, localizations too!!!!
