### ISSUE TITLE
Allow different kinds of significant event

### ISSUE THREAD

**Issue by kengleong** [grizzly/AppRating#4]
Allow different significant event counter. 

**Eg:** Only prompt when the user within the same app "hailed 3 ride sharing rides" OR "paid 5 times through credit card" OR "participated once in a in-app event". Current significant events counter does not allow the differentiation of events. You can only add all of these events together.

**Comment by grizzly** [comment]
Interesting feature. Will try to get this on the feature list.

**Comment by UlanNurmatov** [comment]
Is it possible to check for counters only when userDidSignificantEvent? 
For example, I need the alert to show only after a button is pressed 5 times and 3 days passed. A user can press button 5 times quite soon, but 3 days haven't passed yet. So when 3 days pass, the alert will show up right after the app launch, whereas I need it to be shown only after the button press.
