### ISSUE TITLE
Obj-C Inference Broken

### ISSUE THREAD

**Issue by vrao423** [grizzly/AppRating#8]
Hello, Seems like objc inference was turned off without adding `@obj` annotation to code. Can you please confirm issue and I can submit a PR.

**Comment by grizzly** [comment]
Please send the PR, will test the code.

**Comment by vrao423** [comment]
Was going to work on it today but seems like you already fixed it.

**Comment by vrao423** [comment]
Well...seems like you still need to tag the update. Also probably need to change podspec and update trunk. Don't think I can make these changes.

**Comment by vrao423** [comment]
Also, seems like AppRatingManager is missing `@objc` inference. Submitted a PR.
